### ISSUE TITLE
In mobile view of home page , bottom part is not visible 

### ISSUE THREAD

**Issue by ShravaniAK** [wagtail/wagtail.org#366] opened 2023-02-26 05:04 UTC
In mobile view of home page , bottom part is not visible , on clicking the navbar buttons.
<img width="1425" alt="Screenshot 2023-02-26 at 10 32 15 AM" src="https://user-images.githubusercontent.com/97099574/221393331-a23d1467-9e2f-46dc-83cf-1155ddfe102b.png">

### Steps to Reproduce

1. (for example) Start a new project with `wagtail start myproject`
2. Edit models.py as follows...
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)

### Technical details

-   Python version: Run `python --version`.
-   Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
-   Wagtail version: Look at the bottom of the Settings menu in the Wagtail admin, or run `pip show wagtail | grep Version:`.
-   Browser version: You can use https://www.whatsmybrowser.org/ to find this out.

**Comment by ShravaniAK** [comment] 2023-02-26 05:13
I see that this issue is not only in mobile view but also tablet view,  the bottom text in purple color is only half visible

**Comment by ShravaniAK** [comment] 2023-02-26 09:29
I am working on this this issue

**Comment by MAYANKpandey14** [comment] 2023-04-03 17:00
Hi Everyone,
@ShravaniAK Thank for your contribution to wagtail community for finding this issue in wagtail.org  website. Just wanted to ask you, are you working on this issue currently.

**Comment by thibaudcolas** [comment] 2023-11-04 17:16
Closing as a duplicate of #306. This has nothing to do with the homepage, the menu is like that on all pages.

**Closed by thibaudcolas** 2023-11-04 17:16 UTC
