### ISSUE TITLE
Nav CTA is cropped within mobile menu

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail.org#306] opened 2022-11-04 16:45 UTC
Within the mobile menu’s sub-items, all `nav-cta` components at the bottom of each section are only half-visible when scrolling all the way to the end of the menu.

<img width="1425" alt="Screenshot 2023-02-26 at 10 32 15 AM" src="https://user-images.githubusercontent.com/97099574/221393331-a23d1467-9e2f-46dc-83cf-1155ddfe102b.png">

**Comment by vossisboss** [comment] 2024-11-27 21:57
It looks like removing the Ukraine banner has solved this issue. We were unable to reproduce this item and so we're going to close this issue for now.

**Closed by vossisboss** 2024-11-27 21:57 UTC
Labels: bug, component: Frontend
