### ISSUE TITLE
Request to Update Twitter Icon to X 

### ISSUE THREAD

**Issue by subhajit20** [wagtail/wagtail.org#404] opened 2023-09-14 05:58 UTC
Twitter logo is updated recently and hasnt been updated on the site. I didnt find any issue related to this.

Screenshot
![Wagtail CMS - Django Content Management System - Google Chrome 14-09-2023 11_17_56](https://github.com/wagtail/wagtail.org/assets/99127578/c298e133-d1ef-4010-a989-a7dcc79c9099)

**Comment by laymonage** [comment] 2023-09-14 06:09
Duplicate of #398.

**Closed by laymonage** 2023-09-14 06:09 UTC
